spring:
  application:
    name: restful-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/app}
      database: app
      auto-index-creation: false

logging:
  level:
    ROOT: ${LOG:INFO}